start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-7452\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-7453\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-7454\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-7623\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-7939\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-7962\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-9204\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-9205\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-9206\fuzzing\config.yaml
start python wrapper.py C:\vulnerabilities\imageworsener_reproduce\CVE-2017-9207\fuzzing\config.yaml
