start python.exe wrapper.py C:\vulnerabilities\jasper_reproduce4\CVE-2016-9389\vulnerable\jasper\src\msvc\Win32_Release\imginfo.exe C:\vulnerabilities\jasper_reproduce4\CVE-2016-9389\fuzzing
start python.exe wrapper.py C:\vulnerabilities\jasper_reproduce4\CVE-2016-8883\vulnerable\jasper\src\msvc\Win32_Release\imginfo.exe C:\vulnerabilities\jasper_reproduce4\CVE-2016-8883\fuzzing
start python.exe wrapper.py C:\vulnerabilities\jasper_reproduce4\CVE-2016-8692\vulnerable\jasper\src\msvc\Win32_Release\imginfo.exe C:\vulnerabilities\jasper_reproduce4\CVE-2016-8692\fuzzing
start python.exe wrapper.py C:\vulnerabilities\jasper_reproduce4\CVE-2016-8691\vulnerable\jasper\src\msvc\Win32_Release\imginfo.exe C:\vulnerabilities\jasper_reproduce4\CVE-2016-8691\fuzzing
start python.exe wrapper.py C:\vulnerabilities\jasper_reproduce4\CVE-2016-10251\vulnerable\jasper\src\msvc\Win32_Release\imginfo.exe C:\vulnerabilities\jasper_reproduce4\CVE-2016-10251\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8933\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8933\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-8689_2\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-8689_2\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-8688\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-8688\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-8687\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-8687\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-7166\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-7166\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-6250\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-6250\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-5844\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-5844\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-4809\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-4809\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-10350\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-10350\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2016-10349\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2016-10349\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8934\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8934\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8932\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8932\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8930\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8930\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8928\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8928\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8927\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8927\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8926\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8926\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8925\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8925\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8924\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8924\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8923\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8923\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8922\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8922\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8921\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8921\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8920\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8920\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8919\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8919\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8918\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8918\fuzzing
start python.exe wrapper.py C:\vulnerabilities\libarchive_reproduce\CVE-2015-8915\vulnerable\libarchive\bin\Release\bsdtar.exe C:\vulnerabilities\libarchive_reproduce\CVE-2015-8915\fuzzing
