start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5511\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5511\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7531\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7531\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7533\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7533\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7535\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7535\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7906\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2016-7906\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2016-8866\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2016-8866\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2016-9556\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2016-9556\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5506\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5506\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5508\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5508\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5509\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5509\fuzzing\log.log 
start c:\Python27\python.exe foe2.py -c C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5510\fuzzing\config.yaml -l C:\vulnerabilities\ImageMagick_exploited\CVE-2017-5510\fuzzing\log.log 
